# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: flake8
        args: [--max-line-length=120]
        files: src/*
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest
        language: system
        pass_filenames: false
